# Generated by Django 3.2 on 2022-08-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('email_address', models.EmailField(default=False, max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
